### ISSUE TITLE
Ampersand trickery not supported

### ISSUE THREAD

**Issue by ricksbrown** [vaadin/sass-compiler#15]
In native sass we can compile this:

``` sass
div.layout {
    &50 {
        width: 50%;
    }
    &100 {
        width: 100%;
    }
}
```

To get this:

``` css
div.layout50 {
  width: 50%; }
div.layout100 {
  width: 100%; }
```

For the same input Vaadin sass-compiler gives us an exception: 

```
org.w3c.css.sac.CSSParseException: encountered "50". Was expecting one of: "," "[" "%" "." ":" "{" <HASH> "." "%" <HASH> ":" "[" "," "{"'
```
