### ISSUE TITLE
Brackets are removed within CSS calc statements

### ISSUE THREAD

**Issue by CedricReichenbach** [vaadin/sass-compiler#313]
Brackets within `calc()` statements in CSS should not be touched by the compiler, but are currently removed.

**Example source code:**

```css
.foo {
  width: calc(2 * (3px + 4px));
}
```

**Expected output:**

```css
.foo {
  width: calc(2 * (3px + 4px)); /* -> 14px */
}
```

**Actual output:**

```css
.foo {
  width: calc(2 * 3px + 4px); /* -> 10px */
}
```

This is especially painful because it leads to subtle, hard to detect errors in layouts.
